### PR TITLE
Add new SDK attribute

### PR DESCRIPTION
**Pull request by bramaudi**
This PR add new data attribute for customizing moderator (MOD) badge text.

### CODE REVIEW

**Comment by djyde** [comment]
Could you fix the conflict? BTW, have you tested it?

**Comment by bramaudi** [comment]
I have tested and there is no problem, but if what you mean is unit test i couldn't find where the files is.

**Comment by djyde** [comment]
I think we could make `MOD` to a locale variable. Then you can modify this string in `window.CUSDIS_LOCALE`. How do you think?

**Comment by bramaudi** [comment]
That's great idea, but in my opinion it is need extra step if compared with set data attribute to just custom single word, isn't it?

With data attribute we can do more dynamically, even if use different MOD for each Cusdis instance as example.

**Comment by djyde** [comment]
> That's great idea, but in my opinion it is need extra step if compared with set data attribute to just custom single word, isn't it?
> 
> With data attribute we can do more dynamically, even if use different MOD for each Cusdis instance as example.

But what if next time someone want to customize text of the `Comment` button? Should we provide a data-comment-button?

**Comment by bramaudi** [comment]
No, that one is included as language data, but MOD is not then we can modify it with data-mod, that's my point.

But, i agree with you, i will put MOD as language data.

**Comment by djyde** [comment]
@bramaudi a29f0b1b

**Pull request closed without merging**
